### ISSUE TITLE
Compatibility with Craft Commerce v.3

### ISSUE THREAD

**Issue by focalinteractive** [mediabeastnz/craft-commerce-click-and-collect#3]
Is this plugin compatible with Craft Commerce v.3?

**Comment by mylesthedev** [comment]
@focalinteractive just testing my commerce products this week. I'll let you know shortly :)

**Comment by goodmixer** [comment]
Any update on Craft Commerce 3 compatability?

**Comment by mylesthedev** [comment]
Sorry this isn't compatible yet, it's on my list to update soon though

**Comment by green17** [comment]
Hi @mediabeastnz any time frame on the update keen to look at using this.

**Comment by john-henry** [comment]
I believe there was a small fix to get this working here https://github.com/mediabeastnz/craft-commerce-click-and-collect/pull/4

combined with https://github.com/mediabeastnz/craft-commerce-click-and-collect/pull/1 you should be golden

**Comment by green17** [comment]
@john-henry thanks so much for looking at it, we add this back in to test but when we added a store address we get this: 

Return value of mediabeastnz\ClickAndCollect\models\StoreModel::getAddress() must be an instance of mediabeastnz\ClickAndCollect\models\object, instance of craft\commerce\models\Address returned

**Comment by john-henry** [comment]
@green17 PHP 7.1?

**Comment by john-henry** [comment]
The hinting used for `: object` is only compatible with PHP 7.2 +. I just removed it in my latest change to my PR if you want to test that @green17

**Comment by green17** [comment]
@john-henry looks good so far thanks.

**Comment by mylesthedev** [comment]
closed with #4
