### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by AndrewMac** [mediabeastnz/craft-commerce-click-and-collect#5]
Hello there. I'm afraid I can't change anything in settings. When I click save they all revert to the original defaults.

Is this anything to do with Commerce 3 compatibility. And is there any word on that yet?

**Comment by AndrewMac** [comment]
Sorry, just saw that this has apparently been addressed in a pull request. 
Is @mediabeastnz still around? I hope he's okay.

**Comment by mylesthedev** [comment]
Sorry - limited time for plugin updates currently 😞

**Comment by AndrewMac** [comment]
Glad to hear you're okay (can't be too sure these days!).
And thanks so much for the update. It all works as expected now :-)
